//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Calculator.NET")]
[assembly: System.Reflection.AssemblyProduct("Calculator.NET")]
[assembly: System.Reflection.AssemblyDescription("Calculator that can parse math expression.")]
[assembly: System.Reflection.AssemblyCompany("LoreSoft")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2015 Paul Welter")]
[assembly: System.Runtime.InteropServices.Guid("43484513-ed81-4a9f-8de4-be3abfe106b0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("1.2.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.2.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.2.0.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyTitle = "Calculator.NET";
    
    internal const string AssemblyProduct = "Calculator.NET";
    
    internal const string AssemblyDescription = "Calculator that can parse math expression.";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2015 Paul Welter";
    
    internal const string Guid = "43484513-ed81-4a9f-8de4-be3abfe106b0";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "1.2.0.0";
    
    internal const string AssemblyFileVersion = "1.2.0.0";
    
    internal const string AssemblyInformationalVersion = "1.2.0.0";
    
    private ThisAssembly() {
    }
}
