//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Calculator.NET")]
[assembly: AssemblyProduct("Calculator.NET")]
[assembly: AssemblyDescription("Calculator that can parse math expression.")]
[assembly: AssemblyCompany("LoreSoft")]
[assembly: AssemblyCopyright("Copyright © 2007 Paul Welter")]
[assembly: Guid("43484513-ed81-4a9f-8de4-be3abfe106b0")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.12")]
[assembly: AssemblyInformationalVersion("1.0.0.12")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyTitle = "Calculator.NET";
    
    internal const string AssemblyProduct = "Calculator.NET";
    
    internal const string AssemblyDescription = "Calculator that can parse math expression.";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2007 Paul Welter";
    
    internal const string Guid = "43484513-ed81-4a9f-8de4-be3abfe106b0";
    
    internal const string AssemblyVersion = "1.0.0.0";
    
    internal const string AssemblyFileVersion = "1.0.0.12";
    
    internal const string AssemblyInformationalVersion = "1.0.0.12";
    
    private ThisAssembly() {
    }
}
