//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("LoreSoft.MathExpressions")]
[assembly: AssemblyProduct("LoreSoft.MathExpressions")]
[assembly: AssemblyDescription("Math Expression Parser.")]
[assembly: AssemblyCompany("LoreSoft")]
[assembly: AssemblyCopyright("Copyright © 2009 Paul Welter")]
[assembly: Guid("348985f4-3fcf-4ec3-b207-6f09e918b297")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.16")]
[assembly: AssemblyInformationalVersion("1.0.0.16")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyTitle = "LoreSoft.MathExpressions";
    
    internal const string AssemblyProduct = "LoreSoft.MathExpressions";
    
    internal const string AssemblyDescription = "Math Expression Parser.";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2009 Paul Welter";
    
    internal const string Guid = "348985f4-3fcf-4ec3-b207-6f09e918b297";
    
    internal const string AssemblyVersion = "1.0.0.0";
    
    internal const string AssemblyFileVersion = "1.0.0.16";
    
    internal const string AssemblyInformationalVersion = "1.0.0.16";
    
    private ThisAssembly() {
    }
}
