//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("LoreSoft.MathExpressions")]
[assembly: System.Reflection.AssemblyProduct("LoreSoft.MathExpressions")]
[assembly: System.Reflection.AssemblyDescription("Math Expression Parser.")]
[assembly: System.Reflection.AssemblyCompany("LoreSoft")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2015 Paul Welter")]
[assembly: System.Runtime.InteropServices.Guid("348985f4-3fcf-4ec3-b207-6f09e918b297")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("1.2.1.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.2.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.2.0.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyTitle = "LoreSoft.MathExpressions";
    
    internal const string AssemblyProduct = "LoreSoft.MathExpressions";
    
    internal const string AssemblyDescription = "Math Expression Parser.";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2015 Paul Welter";
    
    internal const string Guid = "348985f4-3fcf-4ec3-b207-6f09e918b297";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "1.2.0.0";
    
    internal const string AssemblyFileVersion = "1.2.0.0";
    
    internal const string AssemblyInformationalVersion = "1.2.0.0";
    
    private ThisAssembly() {
    }
}
