//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreSoft.MathExpressions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreSoft.MathExpressions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IExpression.Evaluate property can not be null..
        /// </summary>
        internal static string EvaluatePropertyCanNotBeNull {
            get {
                return ResourceManager.GetString("EvaluatePropertyCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function name &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string FunctionNameRegistered {
            get {
                return ResourceManager.GetString("FunctionNameRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of arguments: .
        /// </summary>
        internal static string InvalidArgumentCount {
            get {
                return ResourceManager.GetString("InvalidArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character: .
        /// </summary>
        internal static string InvalidCharacterEncountered {
            get {
                return ResourceManager.GetString("InvalidCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid convertion expression: .
        /// </summary>
        internal static string InvalidConvertionExpression {
            get {
                return ResourceManager.GetString("InvalidConvertionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function name &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidFunctionName {
            get {
                return ResourceManager.GetString("InvalidFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length of array..
        /// </summary>
        internal static string InvalidLengthOfArray {
            get {
                return ResourceManager.GetString("InvalidLengthOfArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid math expression..
        /// </summary>
        internal static string InvalidMathExpression {
            get {
                return ResourceManager.GetString("InvalidMathExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number format: .
        /// </summary>
        internal static string InvalidNumberFormat {
            get {
                return ResourceManager.GetString("InvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operator: .
        /// </summary>
        internal static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid symbol on stack: .
        /// </summary>
        internal static string InvalidSymbolOnStack {
            get {
                return ResourceManager.GetString("InvalidSymbolOnStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function or variable: .
        /// </summary>
        internal static string InvalidVariableEncountered {
            get {
                return ResourceManager.GetString("InvalidVariableEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number for expression: .
        /// </summary>
        internal static string NotEnoughNumbers {
            get {
                return ResourceManager.GetString("NotEnoughNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbalanced parentheses..
        /// </summary>
        internal static string UnbalancedParentheses {
            get {
                return ResourceManager.GetString("UnbalancedParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name conflicts with function &apos;{0}&apos;..
        /// </summary>
        internal static string VariableNameConflict {
            get {
                return ResourceManager.GetString("VariableNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name can only contain letters..
        /// </summary>
        internal static string VariableNameContainsLetters {
            get {
                return ResourceManager.GetString("VariableNameContainsLetters", resourceCulture);
            }
        }
    }
}
